export default EVENTS_DATA = [
    {
        id: 1,
        title: 'Weekly Meeting & Open Lab',
        date: 'Every Thursday',
        time: '3:30 PM – 5:00 PM',
        location: 'E172 (The "Makerspace")',
        description: 'Our regular weekly meeting. We\'ll cover club announcements and Aqua Guardian project updates, followed by open lab time. Work on your projects, ask mentors for help, or just hang out. New members welcome!',
        organizer: 'Dr. Evelyn Reed',
        contact: 'ereed@atholton.edu',
    },
    {
        id: 2,
        title: 'Workshop: Intro to Soldering',
        date: 'Friday, November 14, 2025',
        time: '4:00 PM – 6:00 PM',
        location: 'Electronics Bench (E172)',
        description: 'Learn the fundamentals of through-hole soldering. We\'ll provide practice kits and teach you how to make clean, strong solder joints. No experience necessary. Spots are limited!',
        organizer: 'Jane Doe (Club President)',
        contact: 'jane.doe@student.atholton.edu',
    },
    {
        id: 3,
        title: 'Guest Speaker: Chesapeake Bay Foundation',
        date: 'Tuesday, November 25, 2025',
        time: '1:00 PM (Lunch Period)',
        location: 'Auditorium',
        description: 'A field researcher from the Chesapeake Bay Foundation will discuss the importance of water quality monitoring and how data from projects like Aqua Guardian can help. Pizza provided.',
        organizer: 'Dr. Evelyn Reed',
        contact: 'ereed@atholton.edu',
    },
];
